[DYCLOUD]2024-12-02 08:22:02.626	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/kubernetes/clusterManager/cluster/k8s_cluster.go:386	获取命名空间失败!	{"error": "Get \"https://192.168.31.50:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=devops%2Fmanage%3Ddevops%2Cdevops%2Fcluster-id%3D1d79cb51-284a-4a99-9508-f7bac8a46cbb%2Cdevops%2Fusername%3Dadmin\": dial tcp 192.168.31.50:6443: i/o timeout"}
[DYCLOUD]2024-12-02 08:28:49.481	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-12-02 08:41:05.118	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-12-02 08:49:12.332	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-12-02 09:31:49.294	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/initialize/redis.go:31	redis connect ping failed, err:	{"name": "", "error": "MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error."}
[DYCLOUD]2024-12-02 09:32:27.380	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 09:34:24.371	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-12-02 09:44:41.730	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-12-02 09:58:58.665	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 09:59:28.119	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/initialize/redis.go:31	redis connect ping failed, err:	{"name": "", "error": "MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error."}
[DYCLOUD]2024-12-02 10:00:42.940	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 10:21:28.477	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 10:22:28.792	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 10:29:17.793	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 10:49:10.751	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 11:17:51.980	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 13:04:21.713	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 13:10:00.809	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 13:10:40.369	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/cicd/pipelines.go:36	执行失败!	{"error": "Error 1054 (42S22): Unknown column 'env_code' in 'where clause'"}
[DYCLOUD]2024-12-02 13:11:33.107	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 13:14:30.665	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 14:17:57.720	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 15:02:54.000	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/core/server.go:41	accept tcp [::]:8888: use of closed network connection
[DYCLOUD]2024-12-02 16:27:55.903	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-12-02 16:28:03.990	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-12-02 16:29:30.025	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/workload/pod/k8s_pod.go:99	the server could not find the requested resource (get pods.metrics.k8s.io)
