[DYCLOUD]2024-11-15 09:47:19.826	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:19.827	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/network.go:33	获取网络列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:19.828	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:19.828	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:19.828	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/container.go:39	获取容器列表失败:	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:19.828	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:19.828	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:19.829	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/volume.go:33	获取存储卷列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:19.829	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/system.go:29	获取系统信息失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:19.829	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/image.go:33	获取镜像列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:22.618	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:22.619	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/image.go:33	获取镜像列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:23.489	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:23.489	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/container.go:39	获取容器列表失败:	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:23.489	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:23.490	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/image.go:33	获取镜像列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:23.490	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:23.490	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:23.490	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/volume.go:33	获取存储卷列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:23.490	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/system.go:29	获取系统信息失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:23.490	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:23.490	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/network.go:33	获取网络列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:27.893	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:27.893	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/network.go:33	获取网络列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:28.635	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:28.635	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/docker/docker/client.go:35	record not found
[DYCLOUD]2024-11-15 09:47:28.635	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/volume.go:33	获取存储卷列表失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 09:47:28.635	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/docker/system.go:29	获取系统信息失败!	{"error": "host is not found"}
[DYCLOUD]2024-11-15 11:24:40.753	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/kubernetes/deployments.go:42	获取失败: record not found
[DYCLOUD]2024-11-15 11:24:40.753	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:44	record not found
[DYCLOUD]2024-11-15 11:24:42.351	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-11-15 11:24:43.868	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero_tasks.go:164	获取失败:the server could not find the requested resource (get schedules.velero.io)
[DYCLOUD]2024-11-15 11:24:43.868	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s-velero_restore.go:52	获取失败:the server could not find the requested resource (get restores.velero.io)
[DYCLOUD]2024-11-15 11:24:43.868	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero_record.go:43	获取失败:the server could not find the requested resource (get backups.velero.io)
[DYCLOUD]2024-11-15 11:24:43.870	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:372	获取失败!	{"error": "the server could not find the requested resource (get restores.velero.io)"}
[DYCLOUD]2024-11-15 11:24:43.870	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:232	获取失败!	{"error": "the server could not find the requested resource (get backups.velero.io)"}
[DYCLOUD]2024-11-15 11:24:43.870	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:145	获取失败!	{"error": "the server could not find the requested resource (get schedules.velero.io)"}
[DYCLOUD]2024-11-15 13:05:11.012	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/workload/deployment/k8s_deployment.go:82	MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[DYCLOUD]2024-11-15 13:05:16.913	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/workload/deployment/k8s_deployment.go:82	MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[DYCLOUD]2024-11-15 13:05:17.034	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/workload/deployment/k8s_deployment.go:82	MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[DYCLOUD]2024-11-15 13:05:18.709	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/workload/deployment/k8s_deployment.go:82	MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[DYCLOUD]2024-11-15 13:05:18.840	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/workload/deployment/k8s_deployment.go:82	MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[DYCLOUD]2024-11-15 13:09:16.503	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero.go:94	clusterrolebindings.rbac.authorization.k8s.io "velero" already exists
[DYCLOUD]2024-11-15 13:09:16.504	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:178	创建失败!	{"error": "clusterrolebindings.rbac.authorization.k8s.io \"velero\" already exists"}
[DYCLOUD]2024-11-15 13:09:45.250	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero.go:94	clusterrolebindings.rbac.authorization.k8s.io "velero" already exists
[DYCLOUD]2024-11-15 13:09:45.250	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:178	创建失败!	{"error": "clusterrolebindings.rbac.authorization.k8s.io \"velero\" already exists"}
[DYCLOUD]2024-11-15 13:09:53.965	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/utils/kubernetes/deployments.go:57	record not found
[DYCLOUD]2024-11-15 13:09:53.965	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero.go:249	record not found
[DYCLOUD]2024-11-15 13:16:21.482	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero.go:94	clusterrolebindings.rbac.authorization.k8s.io "velero" already exists
[DYCLOUD]2024-11-15 13:16:21.483	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:178	创建失败!	{"error": "clusterrolebindings.rbac.authorization.k8s.io \"velero\" already exists"}
[DYCLOUD]2024-11-15 13:17:04.845	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero.go:94	clusterrolebindings.rbac.authorization.k8s.io "velero" already exists
[DYCLOUD]2024-11-15 13:17:04.846	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:178	创建失败!	{"error": "clusterrolebindings.rbac.authorization.k8s.io \"velero\" already exists"}
[DYCLOUD]2024-11-15 13:22:17.044	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero_record.go:104	获取失败:backups.velero.io "dujie-test-20241115051956" not found
[DYCLOUD]2024-11-15 13:22:17.045	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:266	删除失败!	{"error": "backups.velero.io \"dujie-test-20241115051956\" not found"}
[DYCLOUD]2024-11-15 13:22:19.166	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero_tasks.go:75	获取失败:schedules.velero.io "dujie-test" not found
[DYCLOUD]2024-11-15 13:22:19.167	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:65	删除失败!	{"error": "schedules.velero.io \"dujie-test\" not found"}
[DYCLOUD]2024-11-15 13:22:28.809	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/velero/k8s_velero.go:94	clusterrolebindings.rbac.authorization.k8s.io "velero" already exists
[DYCLOUD]2024-11-15 13:22:28.810	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/velero/k8s_velero_tasks.go:178	创建失败!	{"error": "clusterrolebindings.rbac.authorization.k8s.io \"velero\" already exists"}
[DYCLOUD]2024-11-15 13:30:28.758	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
