[DYCLOUD]2024-11-13 09:39:33.783	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/kubernetes/clusterManager/cluster/k8s_cluster.go:386	获取命名空间失败!	{"error": "Get \"https://192.168.31.40:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=devops%2Fmanage%3Ddevops%2Cdevops%2Fcluster-id%3D5a24c167-7abc-4e00-88ae-ded3615d1d9f%2Cdevops%2Fusername%3Dadmin\": dial tcp 192.168.31.40:6443: connect: connection refused"}
[DYCLOUD]2024-11-13 14:45:55.151	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/cicd/applications.go:91	执行失败!	{"error": "record not found"}
[DYCLOUD]2024-11-13 14:48:56.153	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/cicd/applications.go:91	执行失败!	{"error": "record not found"}
